/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IUser } from "../../structures/users/IUser";

/**
 * Read user
 *
 * @author Switch
 *
 * @controller UsersController.at
 * @path GET /users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(connection: IConnection): Promise<at.Output> {
  return !!connection.simulate
    ? at.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        path: at.path(),
      });
}
export namespace at {
  export type Output = IUser;

  export const METADATA = {
    method: "GET",
    path: "/users",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/users";
  export const random = (g?: Partial<typia.IRandomGenerator>): IUser =>
    typia.random<IUser>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
