version: '3.8'

services:
  kliber_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'